[package]
name = "match_game_score_timestamps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#[:: Main ::]
rand = "0.8.5"
